### ISSUE TITLE
Backup the etcd database

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard-on-prem#182]
See https://etcd.io/docs/v3.5/op-guide/recovery/ for more informations. The database can then be backup with velero

Draft:

```bash
ETCDCTL_API=3 etcdctl \
  --endpoints=https://127.0.0.1:2379 \
  --cacert=/etc/kubernetes/pki/etcd/ca.crt \
  --cert=/etc/kubernetes/pki/etcd/server.crt \
  --key=/etc/kubernetes/pki/etcd/server.key \
  snapshot save /backup/etcd-snapshot.db
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-snapshot-cron
spec:
  schedule: "0 */6 * * *" # Toutes les 6 heures
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etcd-backup
              image: quay.io/coreos/etcd:latest
              command:
                - /bin/sh
                - -c
                - |
                  export ETCDCTL_API=3
                  etcdctl \
                    --endpoints=https://127.0.0.1:2379 \
                    --cacert=/etc/etcd/pki/ca.crt \
                    --cert=/etc/etcd/pki/server.crt \
                    --key=/etc/etcd/pki/server.key \
                    snapshot save /backup/etcd-snapshot-$(date +%F-%H%M%S).db
              volumeMounts:
                - mountPath: /backup
                  name: backup-vol
                - mountPath: /etc/etcd/pki
                  name: etcd-certs
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: backup-vol
              persistentVolumeClaim:
                claimName: etcd-backup-pvc
            - name: etcd-certs
              secret:
                secretName: etcd-client-certs
```

```bash
kubectl create secret generic etcd-client-certs \
  --from-file=ca.crt=/etc/kubernetes/pki/etcd/ca.crt \
  --from-file=server.crt=/etc/kubernetes/pki/etcd/server.crt \
  --from-file=server.key=/etc/kubernetes/pki/etcd/server.key
```
