### ISSUE TITLE
Deploy pgadmin to preview our databases and clusters

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard-on-prem#40]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@exemple.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "votre_mot_de_passe"


apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
```
